language: cpp
matrix:
    include:
        - os: osx
          osx_image: xcode9.3
          compiler: clang
          
        - os: osx
          osx_image: xcode9.4
          compiler: clang
          
        - os: osx
          osx_image: xcode10.1
          compiler: clang

        - os: osx
          osx_image: xcode10.2
          compiler: clang

        - os: osx
          osx_image: xcode10.3
          compiler: clang

        - os: osx
          osx_image: xcode11
          compiler: clang

script:
    - brew update
    - brew install viva64/pvs-studio/pvs-studio-beta
    - brew test pvs-studio-beta
    - brew remove pvs-studio-beta
    - brew install pvs-studio
    - brew test pvs-studio
    - brew remove pvs-studio
